### PR TITLE
FS-17: Dependency security updates

### PR DESCRIPTION
**Pull request by byrond**
### Jira Ticket

https://palantir.atlassian.net/browse/FS-17

### Description 
- Integration branch with automated security fixes for:
  * macaddress (no longer in `yarn.lock` after react-scripts update; `css-loader` no longer requires it)
  * handlebars
  * fstream

- Updates https://github.com/palantirnet/create-react-app (react-scripts) with new versions of `css-loader`, `postcss-loader`, and `jest` to address security issues in `js-yaml`.
- Updates `eslint` dependency  for `js-yaml` security update.
- Updates `node-sass-chokidar` for `tunnel-agent` security update.
- See additional updates to packages here: https://github.com/palantirnet/federated-search-react/pull/45/files

## Testing

- `yarn install`
- `yarn why handlebars`
- `yarn why fstream`
- `yarn why js-yaml`
- `yarn why tunnel-agent`
- Notice none of the installed versions are affected by security vulnerabilities.
- `yarn start`
- Verify React app development functions as expected using this branch.

## To do

- [ ] Create a release for `@palantirnet/react-scripts` and update this PR.

### CODE REVIEW

**Comment by agentrickard** [comment]
@byrond What's the test process for this?

**Comment by byrond** [comment]
@agentrickard, I think the best way to test is to merge with #46 and run through the steps in both PRs.

**Comment by byrond** [comment]
Also, I just added a todo for creating a new release of `react-scripts` once we verify this is working. We can then change this PR to use that release instead of the branch.

**Comment by agentrickard** [comment]
OK. this tests out and is ready for merge. What do we have to do for https://github.com/palantirnet/create-react-app? @byrond

**Comment by agentrickard** [comment]
@byrond I take that back. It is NOT ready for merge. When I had this package set, `yarn build` throws the following error:

```
Rendering Complete, saving .css file...
Wrote CSS to /Applications/MAMP/htdocs/federated-search-react/src/styles.css
Wrote 1 CSS files to /Applications/MAMP/htdocs/federated-search-react/src/
$ react-scripts build
Creating an optimized production build...
Failed to compile.

./src/styles.css
Module build failed: ModuleBuildError: Module build failed: ValidationError: CSS Loader Invalid Options

options should NOT have additional properties
    at <anonymous>


error Command failed with exit code 1.
```

**Comment by byrond** [comment]
I saw the following on `yarn install`:
`warning "@palantirnet/react-scripts > css-loader@2.1.1" has incorrect peer dependency "webpack@^4.0.0".`
So, I updated `webpack` to version 4 in `react-scripts`. Then, `yarn build` failed with the following error:
```
/Users/byronduvall/federated-search-react/node_modules/webpack/lib/webpack.js:187
			throw new RemovedPluginError(errorMessage);
			^

Error: webpack.optimize.UglifyJsPlugin has been removed, please use config.optimization.minimize instead.
```

There were several warnings during `yarn install` after the `webpack` update:
```
warning "@palantirnet/react-scripts > babel-loader@7.1.2" has incorrect peer dependency "webpack@2 || 3".
warning "@palantirnet/react-scripts > extract-text-webpack-plugin@3.0.2" has incorrect peer dependency "webpack@^3.1.0".
warning "@palantirnet/react-scripts > file-loader@1.1.6" has incorrect peer dependency "webpack@^2.0.0 || ^3.0.0".
warning "@palantirnet/react-scripts > html-webpack-plugin@2.30.1" has incorrect peer dependency "webpack@1 || ^2 || ^2.1.0-beta || ^2.2.0-rc || ^3".
warning "@palantirnet/react-scripts > sw-precache-webpack-plugin@0.11.4" has incorrect peer dependency "webpack@^1 || ^2 || ^2.1.0-beta || ^2.2.0-beta || ^3".
warning "@palantirnet/react-scripts > webpack-dev-server@2.9.4" has incorrect peer dependency "webpack@^2.2.0 || ^3.0.0".
warning "@palantirnet/react-scripts > webpack-manifest-plugin@1.3.2" has incorrect peer dependency "webpack@1 || 2 || 3".
warning "@palantirnet/react-scripts > webpack-dev-server > webpack-dev-middleware@1.12.2" has incorrect peer dependency "webpack@^1.0.0 || ^2.0.0 || ^3.0.0".
```
I updated those dependencies until I was down to one warning:
`warning "@palantirnet/react-scripts > extract-text-webpack-plugin@3.0.2" has incorrect peer dependency "webpack@^3.1.0".`

`yarn build` still fails with the "webpack.optimize.UglifyJsPlugin has been removed" error. I'm thinking we'll need to pull in some upstream `react-scripts` updates instead of updating its dependencies individually.

**Comment by agentrickard** [comment]
That is probably true.

**Comment by russom-woldezghi** [comment]
I was able to follow along the comments above (being able to reproduce some of the feedback given). Below is an overview of the errors I was getting and addressing along the way. I have added all the steps that helped me get things updated and running. 

I was however getting an `install` related error when I ran `yarn install`. See below the for the output I was getting: 

```
federated-search-react git:(dependency-security-updates) yarn install
* yarn install v1.21.1
* [1/4] 🔍  Resolving packages...
* [2/4] 🚚  Fetching packages...
* error Couldn't find match for "cb80083da8c777733f0066babef78b54c4cc6766" in "refs/heads/0.9.x,refs/heads/aisensiy-master,refs/heads/custom-react-scripts-symlink,refs/heads/gaearon-patch-1,refs/heads/gaearon-patch-4,refs/heads/master,refs/heads/next,refs/heads/revert-3832-remove-cssm-docs,refs/heads/security-updates,refs/heads/workaround-jest-issue,refs/tags/babel-preset-react-app@0.2.1,refs/tags/babel-preset-react-app@1.0.0,refs/tags/babel-preset-react-app@2.0.0,refs/tags/babel-preset-react-app@2.1.0,refs/tags/babel-preset-react-app@2.1.1,refs/tags/babel-preset-react-app@2.2.0,refs/tags/babel-preset-react-app@3.0.0,refs/tags/babel-preset-react-app
```

Running `yarn upgrade` helped me with this issue/error above. After removing the `node_modules` folder and running yarn’s `install` and `start` command, I started getting this plugin 
error below:  
```
* Would you like to run the app on another port instead? Yes
* Plugin could not be registered at 'html-webpack-plugin-before-html-processing'. Hook was not found.
* BREAKING CHANGE: There need to exist a hook at 'this.hooks'. To create a compatibility layer for this hook, hook into 'this._pluginCompat'.
* error Command failed with exit code 1.
* info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
* ERROR: "start-js" exited with 1.
* error Command failed with exit code 1.
* info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
* Command failed: /Users/woldezghi/.yvm/versions/v1.22.0/bin/yarn.js start
```

Not sure if this is correct but running these command, to remove and re-add the `palantirnet/create-react-app` repo helped me. A specific commit was necessary as it seems it wasn’t getting the right/recent relates. We might need to do more investigation around this issue also.   
```
yarn remove @palantirnet/react-scripts
yarn add https://github.com/palantirnet/create-react-app#df8e7ff41a831da6ae8de091de5dcd500fec30b3
```

Lastly, I ran `yarn upgrade-interactive` to update any lingering packages that needed to be updated. Here is the before and after:  

### Before: 

Screen Shot 2020-02-06 at 3 56 59 PM

```
Package                    Current Wanted  Latest  Package Type    URL                                                                                       
@palantirnet/react-scripts 1.1.3   exotic  exotic  devDependencies https://github.com/palantirnet/create-react-app#jesconstantine-react-scripts-v1.1.3-gitpkg
eslint                     4.19.1  4.19.1  6.8.0   devDependencies https://eslint.org                                                                        
eslint-config-airbnb       16.1.0  16.1.0  18.0.1  devDependencies https://github.com/airbnb/javascript                                                      
eslint-plugin-import       2.12.0  2.20.1  2.20.1  devDependencies https://github.com/benmosher/eslint-plugin-import                                         
eslint-plugin-jsx-a11y     6.0.3   6.2.3   6.2.3   devDependencies https://github.com/evcohen/eslint-plugin-jsx-a11y#readme                                  
eslint-plugin-react        7.9.1   7.18.3  7.18.3  devDependencies https://github.com/yannickcr/eslint-plugin-react                                          
gh-pages                   1.2.0   1.2.0   2.2.0   devDependencies https://github.com/tschaub/gh-pages                                                       
moment                     2.21.0  2.21.0  2.24.0  devDependencies http://momentjs.com                                                                       
node-sass-chokidar         1.3.5   1.4.0   1.4.0   devDependencies https://github.com/michaelwayman/node-sass-chokidar#readme                                
npm-run-all                4.1.2   4.1.2   4.1.5   devDependencies https://github.com/mysticatea/npm-run-all                                                 
prop-types                 15.6.1  15.7.2  15.7.2  devDependencies https://facebook.github.io/react/                                                         
query-string               5.0.0   5.0.1   6.10.1  devDependencies https://github.com/sindresorhus/query-string#readme                                       
react                      16.3.2  16.12.0 16.12.0 devDependencies https://reactjs.org/                                                                      
react-animate-height       1.0.2   1.0.2   2.0.20  devDependencies https://github.com/Stanko/react-animate-height                                            
react-aria-live            2.0.2   2.0.2   2.0.5   dependencies    https://github.com/AlmeroSteyn/react-aria-live#readme                                     
react-dates                16.4.0  16.4.0  21.8.0  devDependencies https://github.com/airbnb/react-dates#readme                                              
react-dom                  16.3.2  16.12.0 16.12.0 devDependencies https://reactjs.org/                                                                      
react-with-direction       1.3.0   1.3.0   1.3.1   devDependencies https://github.com/airbnb/react-with-direction#readme                                     
replace-x                  1.5.0   1.5.0   1.7.2   devDependencies https://github.com/Xotic750/replace-x                                                     
solr-faceted-search-react  0.12.1  exotic  exotic  devDependencies https://github.com/palantirnet/solr-faceted-search-react                                  
✨  Done in 0.78s.
```


### After:   

Screen Shot 2020-02-06 at 3 57 48 PM

``` 
 yarn outdated
yarn outdated v1.22.0
info Color legend : 
 "<red>"    : Major Update backward-incompatible updates 
 "<yellow>" : Minor Update backward-compatible features 
 "<green>"  : Patch Update backward-compatible bug fixes
Package                       Current Wanted Latest Package Type    URL                                                                  
@jesconstantine/react-scripts 1.1.3   exotic exotic dependencies    palantirnet/create-react-app#df8e7ff41a831da6ae8de091de5dcd500fec30b3
solr-faceted-search-react     0.12.1  exotic exotic devDependencies https://github.com/palantirnet/solr-faceted-search-react             
✨  Done in 0.73s.

````


I was now be able to get the app up and running at this point by running removing the `node_modules` directory and running `yarn install && yarn start`. 

I noticed packages I have added (and removed before, like the `palantirnet/create-react-app`, are appearing under `dependencies` array instead of `devDepdendenncies` array in the `package.json` file. 

Let me know if the changes introduced to `package.json` introduces any issues moving forward. I suspect we might need to address any residual security updates - might be easier to open a new pr for that. 

### Testing instructions

Just FYI, to test this PR you should be testing by:

- [ ] Pulling down the branch
- [ ] Removing `node_modules` directory
- [ ] Run `yarn install`
- [ ] Run `yarn start`

**Comment by agentrickard** [comment]
```
yarn install v1.21.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error get-caller-file@2.0.5: The engine "node" is incompatible with this module. Expected version "6.* || 8.* || >= 10.*". Got "9.11.2"
```

**Comment by agentrickard** [comment]
```
federated-search-react: yarn install
yarn install v1.21.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@jesconstantine/react-scripts > extract-text-webpack-plugin@3.0.2" has incorrect peer dependency "webpack@^3.1.0".
warning " > babel-loader@8.0.6" has unmet peer dependency "webpack@>=2".
warning " > eslint-config-airbnb@18.0.1" has unmet peer dependency "eslint-plugin-react-hooks@^1.7.0".
warning " > react-dates@21.8.0" has unmet peer dependency "@babel/runtime@^7.0.0".
warning "react-dates > react-with-styles@4.1.0" has unmet peer dependency "@babel/runtime@^7.0.0".
warning "react-dates > react-with-styles-interface-css@6.0.0" has unmet peer dependency "@babel/runtime@^7.0.0".
[4/4] 🔨  Building fresh packages...
✨  Done in 17.21s.
```

**Comment by agentrickard** [comment]
But it _does_ run.

**Comment by agentrickard** [comment]
We also have these two console errors:

```
react-dom.development.js:12357 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: FederatedTextSearchNoAutocomplete
printWarning @ react-dom.development.js:12357
lowPriorityWarningWithoutStack @ react-dom.development.js:12378
./node_modules/react-dom/cjs/react-dom.development.js.ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings @ react-dom.development.js:12548
flushRenderPhaseStrictModeWarningsInDEV @ react-dom.development.js:25689
commitRootImpl @ react-dom.development.js:24937
unstable_runWithPriority @ scheduler.development.js:697
runWithPriority$2 @ react-dom.development.js:12149
commitRoot @ react-dom.development.js:24922
finishSyncRender @ react-dom.development.js:24329
performSyncWorkOnRoot @ react-dom.development.js:24307
scheduleUpdateOnFiber @ react-dom.development.js:23698
updateContainer @ react-dom.development.js:27103
(anonymous) @ react-dom.development.js:27528
unbatchedUpdates @ react-dom.development.js:24433
legacyRenderSubtreeIntoContainer @ react-dom.development.js:27527
render @ react-dom.development.js:27608
onChange @ index.js:113
(anonymous) @ solr-client.js:85
./node_modules/solr-faceted-search-react/src/api/server.js.server.submitQuery @ server.js:43
sendQuery @ solr-client.js:82
searchFromQuerystring @ index.js:47
init @ index.js:129
./src/index.js @ index.js:164
Promise.then (async)
./src/index.js @ index.js:161
__webpack_require__ @ bootstrap b34b2b40c6ddd5b9aef8:707
fn @ bootstrap b34b2b40c6ddd5b9aef8:112
0 @ styles.css?1cd7:26
__webpack_require__ @ bootstrap b34b2b40c6ddd5b9aef8:707
(anonymous) @ bootstrap b34b2b40c6ddd5b9aef8:805
(anonymous) @ bootstrap b34b2b40c6ddd5b9aef8:805
backend.js:6 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: DateInput, FederatedRangeFacet
```

**Comment by russom-woldezghi** [comment]
Thanks @agentrickard. I can look into the issues with unmet dependencies error further. 

Agree with you comment on the extent of addressing these warnings. I should have a better answer to your question in JIRA. 

Regarding the console error, I think that can be handled separately. I can follow-up in a new ticket for that feedback item.

**Comment by russom-woldezghi** [comment]
@agentrickard 

- I have addressed the unmet dependencies (`webpack`, `eslint-plugin-react-hooks` and `babel/runtime`)  by adding them to the `package.json` as `dependencies`. You should not see those warning anymore. 

- Removed `regenerator-runtime` package, doesn’t seem to be needed. 
- Resolved depreciation warnings when running `yarn start` or `yarn build`: 

```       
Passing a string to call() is deprecated and will be illegal in Sass 4.0. Use call(get-function("output-isolation")) instead
```
  
- Added `patch-package` package to apply patches
  - Added `post-install` script to apply patch 
  - Added `patches` folder’
    - Applies to `singularitygs` package. 
  - Package looks like it’s no longer supported. Package readme suggests using CSS Grid: https://github.com/at-import/Singularity#-singularity-is-no-longer-maintained-css-grid-is-nice-you-should-use-that-instead

- Downgraded `replace-x` package to `1.5.0` release. The most recent version was breaking the `yarn build` command. 

- Was getting npm warnings about mismatched binaries. This command: 
`npm config set scripts-prepend-node-path true` cleared the issue for me locally. Might need to be run to clear the message on other environments:   

Error message:

````
  npm WARN lifecycle The node binary used for scripts is /var/folders/1d/drdhrvj143z4_tzstt8ccs2m0000gp/T/yarn--1581264487540-0.583865012581062/node but npm is using /Users/{username}/.nvm/versions/node/v10.15.3/bin/node itself. Use the --scripts-prepend-node-path option to include the path for the node binary npm was executed with 
````

Let me know if the `install`, `start` or `build` commands are throwing any errors or warnings.

**Comment by agentrickard** [comment]
This all builds correctly _and_ runs in Drupal properly.

Woot!

**Pull request merged**
