### PR TITLE
FS-27: Security alert for webpack-dev-server and mem

### PR DESCRIPTION
**Pull request by russom-woldezghi**
## Ticket

[FS-27: Update mem and webpack-dev-server](https://palantir.atlassian.net/browse/FS-27)


## Description
- Resolves security alerts warnings for `webpack-dev-server` and `mem`
- Switched packages to `react-scripts` from `@palantirnet/react-scripts`. The `@palantirnet/react-scripts` was causing a majority of the security alerts. It doesn't seem like it being used other than supplying an important custom variable value. The `@palantirnet/react-scripts`package  was mostly adding its own `include` value in the `webpack.config.js` file. It was forked from `react-scripts` package and was on version `1.1.14` - hence the large volume of security warnings. This might need to be further explored and not in a patch.
    - Replaces `include` value with `[paths.appSrc, fs.realpathSync(paths.appSrc+'/solr-faceted-search-react’)]`
    - Reduces warnings when running `yarn audit`, should be down to one warning (was around 74) coming from `braces` package - which we can tackle that warning in a different ticket.
- Replaces `<a>` links with `<div>` because of validation warning coming from `eslint-plugin-jsx-a11y` package during `yarn start`. Currently, `<a>` didn’t have `href` attribute. That was causing validation warnings during `yarn start` and showing on the browser consoles. 

```
Compiled with warnings.

./src/components/list-facet/index.js
  Line 204:13:  The href attribute is required for an anchor to be keyboard accessible. Provide a valid, navigable address as the href value. If you cannot provide an href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid
  Line 235:9:   The href attribute is required for an anchor to be keyboard accessible. Provide a valid, navigable address as the href value. If you cannot provide an href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid

./src/components/results/pagination.js
  Line 27:9:   The href attribute requires a valid value to be accessible. Provide a valid, navigable address as the href value. If you cannot provide a valid href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid
  Line 27:17:  Script URL is a form of eval                                                                                                                                                                                                                                                                                                                                      no-script-url
  Line 67:13:  The href attribute requires a valid value to be accessible. Provide a valid, navigable address as the href value. If you cannot provide a valid href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid
  Line 67:21:  Script URL is a form of eval                                                                                                                                                                                                                                                                                                                                      no-script-url
  Line 75:13:  The href attribute requires a valid value to be accessible. Provide a valid, navigable address as the href value. If you cannot provide a valid href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid
  Line 75:21:  Script URL is a form of eval                                                                                                                                                                                                                                                                                                                                      no-script-url
  Line 84:13:  The href attribute requires a valid value to be accessible. Provide a valid, navigable address as the href value. If you cannot provide a valid href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid
  Line 84:21:  Script URL is a form of eval                                                                                                                                                                                                                                                                                                                                      no-script-url
  Line 92:13:  The href attribute requires a valid value to be accessible. Provide a valid, navigable address as the href value. If you cannot provide a valid href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid
  Line 92:21:  Script URL is a form of eval                                                                                                                                                                                                                                                                                                                                      no-script-url

./src/components/range-facet/index.js
  Line 82:9:  The href attribute is required for an anchor to be keyboard accessible. Provide a valid, navigable address as the href value. If you cannot provide an href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.
```
<img width="1529" alt="Screen Shot 2020-02-12 at 4 58 21 PM" src="https://user-images.githubusercontent.com/541745/74381157-f2bcc480-4db8-11ea-9b0c-66912349a2a8.png">


More info that here: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md


## Testing instruction

- [ ] Pull down code
- [ ]  Remove `nodes_modules`
- [ ]  Ensure your `env.local.js` has `autocomplete` uncommented
- [ ]  Run `yarn && yarn start`
- [ ]  Observe you are not getting href attributes warnings from `eslint-plugin-jsx-a11y` package in the terminal. 
- [ ]  Ensure you only see warnings for relating to `componentWillReceiveProps` and not from `eslint-plugin-jsx-a11y` with warnings about href attributes. 
- [ ]  Perform searches, facet filtering on all the fields visible. Observe for any other warning, asides from DateInput and Autosuggest packages.

### CODE REVIEW

**Comment by agentrickard** [comment]
I am getting:

```
index.js:1 Warning: Failed prop type: checker is not a function
    in FederatedTextSearchAsYouType (at text-search/index.js:10)
    in FederatedTextSearch (at federated-solr-faceted-search.js:143)
    in div (at federated-solr-faceted-search.js:142)
    in div (at federated-solr-faceted-search.js:140)
    in div (at federated-solr-faceted-search.js:103)
    in LiveAnnouncer (at federated-solr-faceted-search.js:102)
    in FederatedSolrFacetedSearch (at src/index.js:135)
```

**Comment by agentrickard** [comment]
On build, I also got:

```
warning "react-scripts > eslint-config-react-app@5.2.0" has incorrect peer dependency "eslint-plugin-flowtype@3.x".
warning "react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
```

Which I think is fixed by #55 ?

**Comment by agentrickard** [comment]
@russom-woldezghi  I am still seeing this error on build `yarn install`

```
warning "react-scripts > eslint-config-react-app@5.2.0" has incorrect peer dependency "eslint-plugin-flowtype@3.x".
warning "react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
```

It does not seem to be causing any issues, however.

**Comment by agentrickard** [comment]
Oddly, I do not get this error on a build of the 3.x branch, so it's something in this PR.

**Comment by agentrickard** [comment]
This issue -- https://github.com/facebook/create-react-app/issues/7759 --  suggests that we can ignore this problem until there is an upstream fix.

**Comment by russom-woldezghi** [comment]
@agentrickard Adding`eslint-plugin-flowtype@3.x` and `typescript@>=2.8.0` packages to `devDependencies` fixed the warnings. Let me know if this works.

**Pull request merged**
